import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./ui/fonts";
import AppProvider from "./ui/AppProvider";

export const metadata: Metadata = {
  title: "Azure OpenAI Chat",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
